[build]
  publish = "public" # Change to "dist" or your build output folder if needed
  command = "npm run build" # Modify if you're not using a build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
